// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ibdwh_emas.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmas = `-- name: CreateEmas :one
INSERT INTO ibdwh.emas (jual, beli, created_at)
VALUES ($1, $2, $3)
RETURNING emas_id, jual, beli, created_at, avg_bpkh
`

type CreateEmasParams struct {
	Jual      pgtype.Numeric   `json:"jual"`
	Beli      pgtype.Numeric   `json:"beli"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateEmas(ctx context.Context, arg CreateEmasParams) (IbdwhEma, error) {
	row := q.db.QueryRow(ctx, createEmas, arg.Jual, arg.Beli, arg.CreatedAt)
	var i IbdwhEma
	err := row.Scan(
		&i.EmasID,
		&i.Jual,
		&i.Beli,
		&i.CreatedAt,
		&i.AvgBpkh,
	)
	return i, err
}
