// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IbdwhEma struct {
	EmasID    pgtype.Int4      `json:"emas_id"`
	Jual      pgtype.Numeric   `json:"jual"`
	Beli      pgtype.Numeric   `json:"beli"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	AvgBpkh   pgtype.Numeric   `json:"avg_bpkh"`
}
