// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateEmas(ctx context.Context, arg CreateEmasParams) (IbdwhEma, error)
}

var _ Querier = (*Queries)(nil)
