services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=web_crawler_demo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./_init/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - web-crawler-demo

  web-crawler:
    build: ./web-crawler
    image: web-crawler
    container_name: web-crawler
    restart: unless-stopped
    volumes:
      - ./web-crawler/config.json:/app/config.json
    depends_on:
      - postgres
    networks:
      - web-crawler-demo

networks:
  web-crawler-demo:
    driver: bridge
    name: web-crawler-demo

volumes:
  postgres-data:
